version: '3.9'

services:
    app:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "${APP_PORT}:8000"
        command: ["sh", "/app/entrypoint.sh"]
        env_file:
            - ../.env
        depends_on:
            - postgres
        volumes:
            -   ..:/app/