version: '3.9'

services:
    postgres:
        image: postgres
        container_name: django_postgres
        restart: on-failure
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_NAME=${POSTGRES_NAME}

volumes:
    postgres_data: